version: "3"

services:
  bitscreenapp:
    image: keykoio/bitscreen-client:latest
    ports:
      - 3030:3030
    links:
      - db
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: bitscreen
      DB_NAME: bitscreen
      DB_PASSWORD: bitscreen

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: bitscreen
      POSTGRES_PASSWORD: bitscreen
      POSTGRES_DB: bitscreen
