version: '3.1'
services:
  bitscreen-api:
    image: murmurationlabs/bitscreen-backend:latest
    restart: unless-stopped
    environment:
      - SENDGRID_API_KEY=???
      - JWT_SECRET=dockerDev
      - 'WEB3_STORAGE_TOKEN=???'
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=bitscreen
      - DB_NAME=bitscreen
      - DB_PASSWORD=bitscreen
    networks:
      bitscreen_net:
        ipv4_address: 172.30.1.3
  db:
    image: postgres
    restart: always
    command:
      - postgres
      - '-c'
      - log_statement=all
      - '-c'
      - log_destination=stderr
    environment:
      POSTGRES_USER: bitscreen
      POSTGRES_PASSWORD: bitscreen
      POSTGRES_DB: bitscreen
    networks:
      bitscreen_net:
        ipv4_address: 172.30.1.4
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - '9080:8080'
    networks:
      bitscreen_net:
        ipv4_address: 172.30.1.5
networks:
  bitscreen_net:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
