version: "3"

services:
  bitscreenapp:
    image: keykoio/bitscreen-client:latest
    ports:
      - 3030:3030
    networks:
      backend:
        ipv4_address: 172.15.0.26
    depends_on:
      - db
    environment:
      DB_HOST: "172.15.0.4"
      DB_PORT: 5432
      DB_USERNAME: "bitscreen_api"
      DB_NAME: "bitscreen"
      DB_PASSWORD: "Admin12"
